# Copyright (C) 2009, 2010, Steffen Knollmann
#
# This file is part of `mtree2'.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.


# Select the used toolchain to generate the objects, executables, etc.
# This will set the following variables:
#   CC    :   This is the C compiler.
#   CFLAGS:   Special flags for the C compiler can be set here.
#   DEPCC :   This is a C Preprocessor that will be used to auto-generate
#             dependencies, it is a safe bet to use gcc for that.  No
#             code will be generated with that compiler!
#   LD    :   The linker.
#   AR    :   The archiver.
#   MAKE  :   The make command that will be used.
TOOLCHAIN = "debug"

# Set the flags for each call of the C compiler.  Please only remove the
# standard `-Wall -std=c99' if they are incompatible with your toolchain
# and select the correct ones for your compiler then in the toolchain
# section.
CFLAGS = -Wall -std=c99

# Set the flags used for the C preprocessor.
CPPFLAGS =

# The flags used for the linking process.
LNFLAGS =

# Additionally needed libraries can be specified here.
LIBS = 

# The actual definitions depending on the chosen toolchain
ifeq ($(TOOLCHAIN), "gnu")
	CC = gcc -O2
	DEPCC = gcc
	LD = ld
	AR = ar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "gnu openmp")
	CC = gcc -O2 -fopenmp
	DEPCC = gcc
	LD = ld
	AR = ar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "debug")
	CC = gcc -O0 -g
	DEPCC = gcc
	LD = ld
	AR = ar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "intel")
	CC = icc
	CFLAGS += -g -Wcheck -wd981 -wd161
	DEPCC = icc
	LD = xild
	AR = xiar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "intel fast")
	CC = icc
	CFLAGS += -O3 -fast -xT
	DEPCC = icc
	LD = xild
	AR = xiar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "intel fast openmp")
	CC = icc
	CFLAGS += -wd981 -O3 -fast -xT -openmp
	DEPCC = icc
	LD = xild
	AR = xiar
	MAKE = make
endif

ifeq ($(TOOLCHAIN), "intel openmp")
	CC = icc
	CFLAGS += -Wcheck -wd981 -openmp
	DEPCC = icc
	LD = xild
	AR = xiar
	MAKE = make
endif
